version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0-browsers
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: 
          name: Frontend build
          command: |
            cd frontend && npm install
            
      - run: 
          name: Frontend Lint
          command: |
            cd frontend && npm run lint
      - run:
          name: Deploy Dev to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git dev