version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0-browsers
    
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - cd frontend && v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Install dependencies
          command: |
            cd frontend && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: 
          name: Frontend Lint
          command: |
            cd frontend && npm run lint